---
language: node_js
node_js:
  - "5"

#sudo: false
sudo: required
dist: trusty

# Don't build `beta` branch
branches:
  except:
    - beta
    - production

services:
  - redis-server

notifications:
  email:
    - cray0000@gmail.com
    - omazinov@gmail.com

env:
  global:
    - BROWSER=chrome TIMEOUT=240000
  matrix:
    - only=payingUser

before_install:
  # testers' binaries
  - mkdir -p .test-bin
  - export PATH=$PWD/.test-bin:$PATH

  # phantomjs required by svg-sprite fails to install sometimes. Use 1.9.8 from Travis.
  - PATH=/usr/local/phantomjs-1.9.8/bin:$PATH
  - which chromium-browser
  - which phantomjs
  - which firefox
  - firefox -v
  - npm config set spin false --global
  - npm install -g npm@^3.6

  # Setup access to npm
  - echo "@dmapper:registry=https://registry.npmjs.org/" >> ~/.npmrc
  - echo "//registry.npmjs.org/:_authToken=c84e2ad7-5a9e-4ac3-9a42-fb4d0f81f3e7" >> ~/.npmrc

  # MongoDB v3
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get update
  - sudo apt-get install -y --force-yes mongodb-org-server=3.2.5 mongodb-org-shell=3.2.5

  # Chrome (Chromium)

  # Use latest version of chromium
  - sudo apt-get install -y chromium-browser

  - which chromium-browser
  - chromium-browser --version
  - curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip && unzip chromedriver.zip && chmod a+x chromedriver && mv chromedriver .test-bin/

  - source bin/travis.sh

install:
  - npm install
  - ./node_modules/.bin/grunt build

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Start selenium
  - wget http://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar
  - java -jar selenium-server-standalone-2.52.0.jar > /dev/null 2>&1 &

  - sleep 10

script:
  - 'npm run -s test-full'

after_success:
  - echo "Success"